import Navbar from "@/components/Navbar";
import styles from "./page.module.css";
export default function Page() {
  return (
    <>
      <title>Mauricio Del Castillo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100;400;700&display=swap"
        rel="stylesheet"
      />
      <Navbar></Navbar>
      <p className={styles.blog_title}>work</p>
    </>
  );
}
