"use client";
import Navbar from "@/components/Navbar";
import Post from "@/components/Post";
import styles from "./page.module.css";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, useGLTF, Environment } from "@react-three/drei";

const Model = () => {
  const gltf = useGLTF("./head3.glb");
  return (
    <>
      <OrbitControls enableZoom={false} />
      <primitive
        object={gltf.scene}
        scale={0.5}
        position-y={0.5}
        position-x={0}
        position-z={0}
      />
    </>
  );
};

export default function Page() {
  const headers = [
    "Thoughts...",
    "Journal",
    "Blog",
    "Diary",
    '"The Universal view melts things into a blur." -Emil Cioran',
  ];

  return (
    <>
      <title>Mauricio Del Castillo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100;300;400;500;700&display=swap"
        rel="stylesheet"
      />
      <Navbar></Navbar>
      <div className={styles.canvas_div}>
        <Canvas shadows dpr={[1, 2]} camera={{ position: [0, 0, 4], fov: 50 }}>
          <Model />
          <Environment preset="city" />
        </Canvas>
      </div>
      <div className={styles.home_div}>
        <h1 className={styles.home_title}>{headers[0]}</h1>
      </div>
      <div className={styles.home_main}>
        <Post
          title="Starting things"
          date="Mar 10, 2023"
          body={
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati, explicabo consequuntur aliquid, inventore placeat sit, odio commodi sunt illum voluptate voluptatum? Culpa perferendis reiciendis asperiores distinctio dolorem quae harum nemo! sit amet consectetur adipisicing elit. Obcaecati, explicabo consequuntur? dolorem quae harum nemo! sit!"
          }
        />
        <Post
          title="Starting things"
          date="Mar 10, 2023"
          body={
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati, explicabo consequuntur aliquid, inventore placeat sit, odio commodi sunt illum voluptate voluptatum? Culpa perferendis reiciendis asperiores distinctio dolorem quae harum nemo! sit amet consectetur adipisicing elit. Obcaecati, explicabo consequuntur? dolorem quae harum nemo! sit!"
          }
        />
        <Post
          title="Starting things"
          date="Mar 10, 2023"
          body={
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati, explicabo consequuntur aliquid, inventore placeat sit, odio commodi sunt illum voluptate voluptatum? Culpa perferendis reiciendis asperiores distinctio dolorem quae harum nemo! sit amet consectetur adipisicing elit. Obcaecati, explicabo consequuntur? dolorem quae harum nemo! sit!"
          }
        />
      </div>
    </>
  );
}
