import Head from "next/head";

import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

function Contact() {
  return (
    <div>
      <Head>
        <title>Mauricio Del Castillo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.mainDiv}>
          <Navbar></Navbar>
          <div className={styles.canvas}></div>
        </div>
      </div>
    </div>
  );
}

export default Contact;
