import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import BsLightbulbOff from "react-icons/bs";

function Home() {
  return (
    <div>
      <Head>
        <title>Mauricio Del Castillo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.navVertical}>
          <div>
            <p className={styles.titleText}>
              <Link href="/">Mauricio Del Castillo</Link>
            </p>
            <div className={styles.contentScroll}>
              <div className={styles.navTitles}>
                <p className={styles.navTitleTITLE}>socials</p>
                <p className={styles.navTitle}>
                  <a
                    href="https://twitter.com/hedosntknow"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="social-link"
                  >
                    twitter
                  </a>
                </p>
                <p className={styles.navTitle}>
                  <a
                    href="https://www.instagram.com/mdelcas4/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="social-link"
                  >
                    instagram
                  </a>
                </p>
                <p className={styles.navTitle}>
                  <a
                    href="https://www.linkedin.com/in/mauricio-del-castillo-264611219/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="social-link"
                  >
                    linkedin
                  </a>
                </p>
                <p className={styles.navTitle}>
                  <a
                    href="https://github.com/JJX30"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="social-link"
                  >
                    github
                  </a>
                </p>
              </div>
              <div className={styles.navTitles}>
                <p className={styles.navTitleTITLE}>blog</p>
                <p className={styles.navTitle}>Working on it - 03/14/22</p>
                <p className={styles.navTitle}>Express genius - 03/14/22</p>
                <p className={styles.navTitle}>Next in line - 03/14/22</p>
                <p className={styles.navTitle}>Tub-o-ware - 03/14/22</p>
              </div>
              <div className={styles.navTitles}>
                <p className={styles.navTitleTITLE}>stuff</p>
                <p className={styles.navTitle}>snowglobe</p>
                <p className={styles.navTitle}>gravity</p>
              </div>
            </div>
          </div>
          <iframe
            className={styles.song}
            src="https://open.spotify.com/embed/track/3fsnRK4dEe7NykXL5anAGp?utm_source=generator"
            width="100%"
            height="80"
            frameBorder="0"
            allowfullscreen=""
            allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
          ></iframe>
        </div>
        <div className={styles.mainDiv}>
          <div className={styles.mainNav}>
            <div className={styles.mainNavContent}>
              <Link href="/work">work</Link>
            </div>
            <div className={styles.mainNavContent}>
              <Link href="/work">about</Link>
            </div>
            <div className={styles.mainNavContent}>
              <Link href="/work">contact</Link>
            </div>
          </div>
          <div className={styles.mainCanvas}></div>
        </div>
      </div>
    </div>
  );
}

export default Home;
