import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import logo from "../public/logo.png";
import React, { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import styles from "../styles/Work.module.css";

function Work() {
  return (
    <div>
      <Head>
        <title>Mauricio Del Castillo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.mainDiv}>
          <Navbar></Navbar>
          <div className={styles.project_div}>
            <div className={styles.project_container}>
              <Image
                src={logo}
                width="700px"
                objectFit="cover"
                alt="UltimateAPI"
                className={styles.project_image}
              />
              <div className={styles.project_content}>
                <h1 className={styles.project_content_header}>UltimateAPI</h1>
                <p className={styles.project_content_p}>
                  RESTful API/MERN app which offers access to comprehensive
                  information on UFC fighters. Head to{" "}
                  <a
                    className={styles.project_content_link}
                    href="ultimateapi.tech"
                  >
                    UltimateAPI.tech
                  </a>
                  , create an account, and receive your unique API key.
                  <br />
                  <br />
                  <a
                    href="https://github.com/JJX30/UltimateAPI"
                    target="_blank"
                    rel="noopener noreferrer"
                    className={styles.project_content_link}
                  >
                    Repo (for test account)
                  </a>
                </p>
              </div>
            </div>
            <div className={styles.project_container}>
              <Image
                src={logo}
                width="800px"
                objectFit="cover"
                alt="FGLPsite"
                className={styles.project_image}
              />
              <div className={styles.project_content}>
                <h1 className={styles.project_content_header}>FGLP site</h1>
                <p className={styles.project_content_p}>
                  Official site for the First-Generation Leadership Program, web
                  responsive dynamic site that helps engage with first-gen
                  students and members interested in learning more and applying.
                  <br />
                  <br />
                  <a className={styles.project_content_link} href="fglpuf.com">
                    Link to site
                  </a>
                </p>
              </div>
            </div>
            <div className={styles.project_container}>
              <Image
                src={logo}
                width="700px"
                objectFit="cover"
                alt="UltimateAPI"
                className={styles.project_image}
              />
              <div className={styles.project_content}>
                <h1 className={styles.project_content_header}>ZooCLI</h1>
                <p className={styles.project_content_p}>
                  ZooCLI is a npm package dex-game aiming to teach about animals
                  while showing amazing ASCII art. Give it a whirl it's pretty
                  cute!
                  <br />
                  <br />
                  <a
                    href="https://github.com/JJX30/UltimateAPI"
                    target="_blank"
                    rel="noopener noreferrer"
                    className={styles.project_content_link}
                  >
                    Repo
                  </a>
                  <br />
                  <br />
                  <a
                    className={styles.project_content_link}
                    href="ultimateapi.tech"
                  >
                    Package
                  </a>
                </p>
              </div>
            </div>
            <div className={styles.project_container}>
              <Image
                src={logo}
                width="700px"
                objectFit="cover"
                alt="UltimateAPI"
                className={styles.project_image}
              />
              <div className={styles.project_content}>
                <h1 className={styles.project_content_header}>is-rec-full</h1>
                <p className={styles.project_content_p}>
                  A gym capacity meter for UF gyms. Using Node, Python CV2, and
                  the schools api to answer the age old quesion{" "}
                  <a
                    href="https://github.com/JJX30/UltimateAPI"
                    target="_blank"
                    rel="noopener noreferrer"
                    className={styles.project_content_link}
                  >
                    is-rec-full
                  </a>
                  ?
                  <br />
                  <br />
                  <a
                    className={styles.project_content_link}
                    href="ultimateapi.tech"
                  >
                    Repo
                  </a>
                </p>
              </div>
            </div>
            {/* <Link href="/work">
              <p
                onMouseMove={handleMove}
                onMouseLeave={handleLeave}
                className={styles.text}
              >
                {text}
              </p>
            </Link> */}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Work;
