import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import profilePic from "../public/zombectro.jpeg";
import React, { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import styles from "../styles/Work.module.css";

function Work() {
  const randCharacters =
    "~!@#$%^&*()_+1234567890-=][poiuytrewqasdfghjkl{}?/><mnbvcxz";
  const [text, setText] = useState("bruh");

  const randomString = (length) => {
    let temp = "";
    for (let i = 0; i < length; i++) {
      temp = temp + randCharacters.charAt(Math.floor(Math.random() * 59));
    }
    return temp;
  };
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  const handleMove = async () => {
    for (let i = 0; i < 20; i++) {
      setText((prev) => {
        return randomString(prev.length);
      });
      await wait(2);
      if (i == 19) {
        setText("bruh");
      }
    }
  };

  const handleLeave = () => {
    setText("bruh");
  };

  return (
    <div>
      <Head>
        <title>Mauricio Del Castillo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.mainDiv}>
          <Navbar></Navbar>
          <div className={styles.project_div}>
            <div className={styles.project_container}>
              <Image
                src={profilePic}
                alt="Picture of the author"
                className={styles.project_image}
              />
              <div className={styles.project_content}>
                <h1>project 1</h1>
                <p>this is project 1 it is really cool blah blah </p>
              </div>
            </div>
            <div className={styles.project_container}>
              <div className={styles.project_image}></div>
              <div className={styles.project_content}>
                <h1>project 1</h1>
                <p>this is project 1 it is really cool blah blah </p>
              </div>
            </div>
            <div className={styles.project_container}>
              <div className={styles.project_image}></div>
              <div className={styles.project_content}>
                <h1>project 1</h1>
                <p>this is project 1 it is really cool blah blah </p>
              </div>
            </div>
            <div className={styles.project_container}>
              <div className={styles.project_image}></div>
              <div className={styles.project_content}>
                <h1>project 1</h1>
                <p>this is project 1 it is really cool blah blah </p>
              </div>
            </div>
            {/* <Link href="/work">
              <p
                onMouseMove={handleMove}
                onMouseLeave={handleLeave}
                className={styles.text}
              >
                {text}
              </p>
            </Link> */}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Work;
